### PR TITLE
#50: Make environment variable in bash script persist

### PR DESCRIPTION
**Pull request by snowme34**

### CODE REVIEW

**Comment by dmhacker** [comment]
Rather than using `export SDSCHEDULE_SCRAPE=0`, we could just use `unset SDSCHEDULE_SCRAPE`. It's cleaner; that way we don't persist anything.

Also, I thought running the script from the command line doesn't persist variables? As in exporting a variable from the script won't save it to the CL session.

**Comment by CTrando** [comment]
@snowme34 Can you spend some time and try to find a better way? Ideally there should be a command that runs and scrapes and one that runs without scraping.

**Comment by snowme34** [comment]
> @snowme34 Can you spend some time and try to find a better way? Ideally there should be a command that runs and scrapes and one that runs without scraping.

It's either we let the user set the environment, or we have different docker-compose for different situations, or we separate the scraper from the back-end.

**Comment by CTrando** [comment]
Something as trivial as this should not require such complex solutions!

**Pull request closed without merging**
