### PR TITLE
#11: Adding preliminary interactive scheduling

### PR DESCRIPTION
**Pull request by CTrando**

### CODE REVIEW

**Comment by snowme34** [comment]
Looks fantastic!

Some genuine proposals:

1. Make it clear for user how to save preference

    As a user, when I try to save the changes in interactive calendar, the intuitive way for me is to click the blue "edit" button. But that results in change loss. It would be better if it's easier for users to see how to save (currently it's clicking on the same/active course section twice OR click on a class for different course).

2. Unreadable titles for large courses

    image

    For large course with multiple sections in the same time, the titles become unreadble.

3. Strange shape for inactive sections 

    image

    If there is 2 sections in one time slot and one is not active, it displays strangely.

4. Strange shape for sections from different class

    image

    image

    For non-editing mode, the shape of one of the sections is strange. And the order depends on which one is "edited" later

5. Preference loss after adding/removing class or press "edit" button

    

    The changes made will disappear after adding/removing class

    **ALSO** pressing "edit" button when editing will also remove all the changes users made (no gif recorded)

6. Display Class Type in Popper

    The intuitive thing users expect to see in popper is the type of the class. Is it a lecture or a discussion?

    image

    Or display the title as COURSE LE

    image


7. "Instructor Preference" and "View Class Types"

    As a user, I cannot tell the point of "Instructor Preference" and "View Class Types" since I did not see any changes in the calendar after changing them.

8. "Infinite" Class Change (User is a bad guy)

    

    And React crashes

9. High CPU Usage

    

    Don't know if will slow down significantly on slow devices

    When I try to add some classes, my CPU usage keeps growing to around 67% of the total usage. And that high usage period lasted for around 30 seconds.

-------------------

Will add more

**Comment by CTrando** [comment]
I've already done some of those comments, could you pull and try again?

**Comment by CTrando** [comment]
Next time, can you post follow up comments instead of editing the old ones so I get an email about it? Thanks again for the suggestions, I will try suggestion 1.

For suggestion 2 here is my solution:

If we have 2 modes, ScheduleGenerator and ScheduleBuilder, on ScheduleGenerator if there are conflicts the only way the user can get rid of them is to ignore class types. On ScheduleBuilder, it basically has the same features as ScheduleGenerator; however, the user can add classes and generate their schedule regardless of conflicts.

**Comment by CTrando** [comment]
Also for 1. If I do two modes then I can make the edit button have two features based on what mode the schedule is in - save the user selected classes in Builder Mode and generate again in Generator Mode.

**Comment by CTrando** [comment]
Instructor Preference and Class Types is broken right now and will be fixed in another PR.

**Comment by CTrando** [comment]
For proposal 1: see #70, I'm going to deprecate the feature because it is too much of a hassle to maintain. If a user wants to switch classes, they will have to remove the class and enter a new one. Do you have an argument for or against this?

**Comment by snowme34** [comment]
Nice work! I truly appreciate how you loosen the restriction for auto generation!

image

-----------------------------------------------------------------------

Several modest overtures:

1. (Bug High) Still the performance problem, the following combination requires around 5 minutes to generate:

MATH 10A, 20A, 20B, 20C, 11

Also after the schedule is "generated" and displayed, my chrome still kept running using 50% of CPU for extra 3 minutes

2. (Confusion) When it's generating, user can "restart" or interrupt the generation by editing the schedule

interrpted-generation

Don't know if this is a feature or not. But a user might be surprised (commendation) to see a cancel button for this!

3. (Bug Low) Inaccurate progress of progress circle (user regards it as a fable)

Even the progress circle is filled, the generation is still far from finished. (It took another 1min after the gif to finish generation)



4. (Confusion) Duplicated ID (what is an ID?)

As a user, I cannot tell what an "ID" is in this calendar by intuition. And for some sections, it even duplicates itself!

image

image

5.  (Feature Medium) Could we highlight the conflicts for the users to easily tell what's wrong?

6. (Bug Low) Hidden text makes it look a little bit "unprofessional"

image

I don't know why we need to include those words there but it makes our app look like still in development.

7. (Feature Low) Some class allows the student to go to any of the discussion they want. Might be cool if the user can combine different such schedules as they like

8. (Feature Low) Give the switch a name, like "Edit Mode". It's not direct for users to understand what that switch does.

More to come...

**Pull request closed without merging**
